"""NotificationType — Classifies alerts generated by the notification system."""
from enum import Enum


class NotificationType(str, Enum):
    CASE_CREATED = "case_created"
    COURT_DATE_REMINDER = "court_date_reminder"
    LEGAL_PROCESS_STATUS_CHANGE = "legal_process_status_change"
    LEGAL_PROCESS_OVERDUE = "legal_process_overdue"
    EVIDENCE_UPDATE = "evidence_update"
    APPROVAL_REQUIRED = "approval_required"
    PEER_REVIEW_REQUEST = "peer_review_request"
    PEER_REVIEW_COMPLETE = "peer_review_complete"
    CASE_ASSIGNED = "case_assigned"
    CASE_STATUS_CHANGE = "case_status_change"
    SYSTEM = "system"

    @property
    def display_name(self) -> str:
        return self.value.replace("_", " ").title()

    def __str__(self) -> str:  # noqa: D105
        return self.value
